use clap::Parser;
use std::io::Write;
use std::fs;
use std::io::{self, BufRead};
use std::path::PathBuf;

mod ffi {
    pub mod sys;
}
mod ignore;
mod repo {
    pub mod config;
    pub mod change;
    pub mod commit;
    pub mod branch;
    pub mod patch;
}
mod remote {
    pub mod ops;
    pub mod email;
}
mod registry;

#[derive(Parser, Debug)]
#[command(
    name = "sky",
    author = "Saladin5101",
    version = "1.0.1",
    about = "Lazy developer-friendly version control tool",
    long_about = None
)]
enum SkyCmd {
    #[command(about = "Initialize QuickSky repository")]
    Init,
    #[command(about = "Commit and push to remote repository")]
    Upload {
        #[arg(default_value_t = String::new(), help = "Commit message (optional, auto-generated by default)")]
        message: String,
    },
    #[command(about = "View all commit records")]
    Log,
    #[command(about = "Branch management")]
    Branch {
        #[arg(short = 'a', help = "Create and switch to new branch")]
        add: Option<String>,
        #[arg(short = 'd', help = "Delete branch")]
        delete: Option<String>,
        #[arg(help = "Switch to existing branch")]
        name: Option<String>,
    },
    #[command(about = "Switch to different repository")]
    ChangeTo {
        #[arg(help = "Repository name to switch to")]
        repo_name: String,
    },
    #[command(about = "Rebase commits")]
    Rebase {
        #[arg(long, help = "Rebase all local changes")]
        all: bool,
        #[arg(help = "Date range (YYYY-MM-DD -> YYYY-MM-DD) or 'fuck-base' to undo")]
        range: Option<String>,
    },
    #[command(about = "Edit past commit message")]
    Reload {
        #[arg(help = "Commit SHA to edit")]
        commit_sha: String,
        #[arg(help = "New commit message")]
        message: String,
    },
    #[command(about = "Generate patch from a commit and send it via email")]
    PatchSend {
        #[arg(long, help = "Commit SHA to generate patch from (default: HEAD)")]
        commit: Option<String>,
        #[arg(help = "Patch file path to write/read (optional, defaults to <commit-id>.patch)")]
        patch_file: Option<String>,
        #[arg(long, help = "Recipient email address")]
        to: String,
        #[arg(long, help = "Override email subject (default: commit message)")]
        subject: Option<String>,
        #[arg(long, help = "SMTP host:port (overrides config, e.g. smtp.example.com:587)")]
        smtp: Option<String>,
        #[arg(long, help = "Sender email address (overrides config)")]
        from: Option<String>,
        #[arg(long, help = "SMTP password (overrides config)")]
        pass: Option<String>,
    },
}

fn main() -> anyhow::Result<()> {
    let cmd = SkyCmd::parse();
    match cmd {
        SkyCmd::Init => init()?,
        SkyCmd::Upload { message } => upload(message)?,
        SkyCmd::Log => log()?,
        SkyCmd::Branch { add, delete, name } => branch_cmd(add, delete, name)?,
        SkyCmd::ChangeTo { repo_name } => change_to(repo_name)?,
        SkyCmd::Rebase { all, range } => rebase_cmd(all, range)?,
        SkyCmd::Reload { commit_sha, message } => reload_commit(commit_sha, message)?,
        SkyCmd::PatchSend { commit, patch_file, to, subject, smtp, from, pass } =>
            patch_send(commit, patch_file, to, subject, smtp, from, pass)?,
    }
    Ok(())
}

fn read_line(reader: &mut impl BufRead, prompt: &str) -> anyhow::Result<String> {
    print!("{}", prompt);
    io::stdout().flush()?;
    let mut buf = String::new();
    reader.read_line(&mut buf)?;
    Ok(buf.trim().to_string())
}

/// Initialize repository
fn init() -> anyhow::Result<()> {
    let repo_root = std::env::current_dir()?;
    let config_path = repo_root.join(".quicksky/config.toml");
    if config_path.exists() {
        return Err(anyhow::anyhow!("Repository already initialized: {:?}", config_path));
    }

    let stdin = io::stdin();
    let mut reader = stdin.lock();

    let name       = read_line(&mut reader, "Enter username: ")?;
    let token_raw  = read_line(&mut reader, "Enter PAT/token (leave blank to skip): ")?;
    let token      = if token_raw.is_empty() { None } else { Some(token_raw) };
    let remote_url = read_line(&mut reader, "Enter remote repository URL: ")?;
    let branch_raw = read_line(&mut reader, "Enter main branch name (default: main): ")?;
    let branch     = if branch_raw.is_empty() { "main".into() } else { branch_raw };

    // SMTP (all optional)
    println!("\nSMTP configuration (for sky patch-send) — leave blank to skip:");
    let smtp_host = read_line(&mut reader, "  SMTP host (e.g. smtp.gmail.com): ")?;
    let smtp_cfg = if smtp_host.is_empty() {
        None
    } else {
        let smtp_port_raw = read_line(&mut reader, "  SMTP port (default: 587): ")?;
        let smtp_port = smtp_port_raw.parse::<u16>().unwrap_or(587);
        let smtp_from = read_line(&mut reader, "  Sender email: ")?;
        let smtp_pass_raw = read_line(&mut reader, "  SMTP password (leave blank to skip): ")?;
        let smtp_pass = if smtp_pass_raw.is_empty() { None } else { Some(smtp_pass_raw) };
        Some(repo::config::SmtpConfig {
            host: smtp_host,
            port: smtp_port,
            from: smtp_from,
            password: smtp_pass,
        })
    };

    let config = repo::config::RepoConfig::new(name.clone(), token, remote_url.clone(), branch.clone(), smtp_cfg);
    config.save(&repo_root)?;

    fs::create_dir_all(repo_root.join(".quicksky/commits"))?;

    let repo_name = repo_root.file_name()
        .and_then(|n| n.to_str())
        .unwrap_or("unknown")
        .to_string();
    registry::register_repo(&repo_name, &repo_root)?;

    println!("\n✅ Initialization successful!");
    println!("User: {} | Remote: {} | Branch: {}", name, remote_url, branch);
    println!("Token: {}", if config.user.token.is_some() { "configured" } else { "not set" });
    println!("SMTP: {}", if config.smtp.is_some() { "configured" } else { "not set" });
    println!("Repository '{}' registered for switching", repo_name);
    Ok(())
}

/// Upload changes
fn upload(message: String) -> anyhow::Result<()> {
    let repo_root = std::env::current_dir()?;
    let config = repo::config::RepoConfig::load(&repo_root)?;

    let msg = if message.is_empty() {
        format!("Auto-commit: {}", chrono::Local::now().format("%Y-%m-%d %H:%M"))
    } else {
        message
    };

    println!("🔍 Detecting changes...");
    let commit = repo::commit::Commit::create(&repo_root, &config, &msg)?;

    println!("📤 Pushing to remote...");
    let current_branch = config.branch.current.as_ref().unwrap_or(&config.branch.main).clone();
    remote::ops::push(&config, &current_branch, &commit, &repo_root)?;

    println!("\n✅ Upload successful!");
    println!("Commit ID: {}", commit.id);
    println!("Message: {}", commit.message);
    Ok(())
}

/// View commit history
fn log() -> anyhow::Result<()> {
    let repo_root = std::env::current_dir()?;
    let commits = repo::commit::Commit::load_all(&repo_root)?;

    if commits.is_empty() {
        return Err(anyhow::anyhow!("No commit records available"));
    }

    println!("📜 Commit history (latest first):");
    for (i, commit) in commits.iter().enumerate() {
        println!("\n[{i}] ID: {}", commit.id);
        println!("   Author: {}", commit.author);
        println!("   Timestamp: {}", commit.timestamp);
        println!("   Message: {}", commit.message);
        println!("   Changes:");
        for (path, status) in &commit.changes {
            let status_str = match status {
                repo::change::FileStatus::Added    => "Added",
                repo::change::FileStatus::Modified => "Modified",
                repo::change::FileStatus::Deleted  => "Deleted",
            };
            println!("     - {status_str}: {:?}", path);
        }
    }
    Ok(())
}

/// Branch management command
fn branch_cmd(add: Option<String>, delete: Option<String>, name: Option<String>) -> anyhow::Result<()> {
    let repo_root = std::env::current_dir()?;

    if let Some(branch_name) = add {
        repo::branch::create_and_switch(&repo_root, &branch_name)?;
        println!("✅ Created and switched to branch: {}", branch_name);
    } else if let Some(branch_name) = delete {
        repo::branch::delete(&repo_root, &branch_name)?;
        println!("✅ Deleted branch: {}", branch_name);
    } else if let Some(branch_name) = name {
        repo::branch::switch(&repo_root, &branch_name)?;
        println!("✅ Switched to branch: {}", branch_name);
    } else {
        let current  = repo::branch::get_current(&repo_root)?;
        let branches = repo::branch::list_all(&repo_root)?;
        println!("Current branch: {}", current);
        println!("All branches: {}", branches.join(", "));
    }
    Ok(())
}

/// Switch to different repository
fn change_to(repo_name: String) -> anyhow::Result<()> {
    let repo_path = registry::find_repo(&repo_name)?;
    std::env::set_current_dir(&repo_path)?;
    println!("✅ Switched to repository: {} at {}", repo_name, repo_path.display());
    Ok(())
}

/// Rebase commits
fn rebase_cmd(all: bool, range: Option<String>) -> anyhow::Result<()> {
    let repo_root = std::env::current_dir()?;

    if let Some(range_str) = range {
        if range_str == "fuck-base" {
            repo::branch::undo_rebase(&repo_root)?;
            println!("✅ Rebase undone successfully");
        } else if range_str.contains(" -> ") {
            let dates: Vec<&str> = range_str.split(" -> ").collect();
            if dates.len() == 2 {
                repo::branch::rebase_date_range(&repo_root, dates[0], dates[1])?;
                println!("✅ Rebased commits from {} to {}", dates[0], dates[1]);
            } else {
                return Err(anyhow::anyhow!("Invalid date range format. Use: YYYY-MM-DD -> YYYY-MM-DD"));
            }
        }
    } else if all {
        let config = repo::config::RepoConfig::load(&repo_root)?;
        let branch = config.branch.current.as_ref().unwrap_or(&config.branch.main).clone();
        println!("📥 Pulling from remote...");
        remote::ops::pull(&config, &branch, &repo_root)?;
        repo::branch::rebase_all(&repo_root)?;
        println!("✅ Pulled remote changes and rebased local commits");
    } else {
        return Err(anyhow::anyhow!("Please specify --all or date range"));
    }
    Ok(())
}

/// Edit past commit message
fn reload_commit(commit_sha: String, message: String) -> anyhow::Result<()> {
    let repo_root = std::env::current_dir()?;
    repo::commit::edit_message(&repo_root, &commit_sha, &message)?;
    println!("✅ Updated commit {} with new message: {}", commit_sha, message);
    Ok(())
}

/// Generate patch from commit and send via email
fn patch_send(
    commit_sha: Option<String>,
    patch_file: Option<String>,
    to: String,
    subject: Option<String>,
    smtp_override: Option<String>,
    from_override: Option<String>,
    pass_override: Option<String>,
) -> anyhow::Result<()> {
    let repo_root = std::env::current_dir()?;
    let config = repo::config::RepoConfig::load(&repo_root)?;

    // Resolve commit
    let commit = match commit_sha {
        Some(sha) => repo::commit::Commit::load_all(&repo_root)?
            .into_iter()
            .find(|c| c.id.starts_with(&sha))
            .ok_or_else(|| anyhow::anyhow!("Commit '{}' not found", sha))?,
        None => repo::patch::head_commit(&repo_root)?,
    };

    // Resolve patch file path
    let patch_path = PathBuf::from(
        patch_file.unwrap_or_else(|| format!("{}.patch", &commit.id[..8]))
    );

    // Generate patch if it doesn't already exist
    if !patch_path.exists() {
        println!("📝 Generating patch...");
        repo::patch::format_patch(&repo_root, &commit, &patch_path)?;
        println!("   Written to {}", patch_path.display());
    } else {
        println!("📎 Using existing patch file: {}", patch_path.display());
    }

    // Resolve SMTP config: CLI args override stored config
    let mut smtp = config.smtp.clone()
        .ok_or_else(|| anyhow::anyhow!(
            "No SMTP config found. Run `sky init` again or pass --smtp/--from/--pass"
        ))?;

    if let Some(s) = smtp_override {
        let parts: Vec<&str> = s.splitn(2, ':').collect();
        smtp.host = parts[0].to_string();
        if let Some(port) = parts.get(1) {
            smtp.port = port.parse().unwrap_or(587);
        }
    }
    if let Some(f) = from_override { smtp.from = f; }
    if let Some(p) = pass_override { smtp.password = Some(p); }

    let subject = subject.unwrap_or_else(|| commit.message.clone());

    println!("📧 Sending patch to {}...", to);
    remote::email::send_patch(&smtp, &to, &subject, &patch_path)?;
    println!("✅ Patch sent successfully!");
    Ok(())
}
