use clap::Parser;
// use anyhow::{Result, anyhow};
use std::io::Write;
use std::fs;
use std::io::{self, BufRead};

mod ffi {
    pub mod sys;
}
mod ignore;
mod repo {
    pub mod config;
    pub mod change;
    pub mod commit;
    pub mod branch;
}
mod remote;
mod registry;

#[derive(Parser, Debug)]
#[command(
    name = "sky",
    author = "Saladin5101",
    version = "0.1.0",
    about = "Lazy developer-friendly version control tool",
    long_about = None
)]
enum SkyCmd {
    #[command(about = "Initialize QuickSky repository")]
    Init,
    #[command(about = "Commit and push to remote repository")]
    Upload {
        #[arg(default_value_t = String::new(), help = "Commit message (optional, auto-generated by default)")]
        message: String,
    },
    #[command(about = "View all commit records")]
    Log,
    #[command(about = "Branch management")]
    Branch {
        #[arg(short = 'a', help = "Create and switch to new branch")]
        add: Option<String>,
        #[arg(short = 'd', help = "Delete branch")]
        delete: Option<String>,
        #[arg(help = "Switch to existing branch")]
        name: Option<String>,
    },
    #[command(about = "Switch to different repository")]
    ChangeTo {
        #[arg(help = "Repository name to switch to")]
        repo_name: String,
    },
    #[command(about = "Rebase commits")]
    Rebase {
        #[arg(long, help = "Rebase all local changes")]
        all: bool,
        #[arg(help = "Date range (YYYY-MM-DD -> YYYY-MM-DD) or 'fuck-base' to undo")]
        range: Option<String>,
    },
    #[command(about = "Edit past commit message")]
    Reload {
        #[arg(help = "Commit SHA to edit")]
        commit_sha: String,
        #[arg(help = "New commit message")]
        message: String,
    },
}

fn main() -> anyhow::Result<()> {
    let cmd = SkyCmd::parse();
    match cmd {
        SkyCmd::Init => init()?,
        SkyCmd::Upload { message } => upload(message)?,
        SkyCmd::Log => log()?,
        SkyCmd::Branch { add, delete, name } => branch_cmd(add, delete, name)?,
        SkyCmd::ChangeTo { repo_name } => change_to(repo_name)?,
        SkyCmd::Rebase { all, range } => rebase_cmd(all, range)?,
        SkyCmd::Reload { commit_sha, message } => reload_commit(commit_sha, message)?,
    }
    Ok(())
}

/// Initialize repository
fn init() -> anyhow::Result<()> {
    let repo_root = std::env::current_dir()?;
    let config_path = repo_root.join(".quicksky/config.toml");
    if config_path.exists() {
        return Err(anyhow::anyhow!("Repository already initialized: {:?}", config_path));
    }

    let stdin = io::stdin();
    let mut reader = stdin.lock();

    // Read username
    print!("Enter username: ");
    io::stdout().flush()?;
    let mut name = String::new();
    reader.read_line(&mut name)?;
    let name = name.trim().to_string();

    // Read remote URL
    print!("Enter remote repository URL: ");
    io::stdout().flush()?;
    let mut remote_url = String::new();
    reader.read_line(&mut remote_url)?;
    let remote_url = remote_url.trim().to_string();

    // Read main branch name
    print!("Enter main branch name (default: main): ");
    io::stdout().flush()?;
    let mut branch = String::new();
    reader.read_line(&mut branch)?;
    let branch = branch.trim().to_string();
    let branch = if branch.is_empty() { "main".into() } else { branch };

    // Save configuration
    let config = repo::config::RepoConfig::new(name.clone(), remote_url.clone(), branch.clone());
    config.save(&repo_root)?;

    // Initialize commit record directory
    fs::create_dir_all(repo_root.join(".quicksky/commits"))?;
    
    // Register repository in global registry
    let repo_name = repo_root.file_name()
        .and_then(|n| n.to_str())
        .unwrap_or("unknown")
        .to_string();
    registry::register_repo(&repo_name, &repo_root)?;

    println!("\n✅ Initialization successful!");
    println!("User: {} | Remote: {} | Main branch: {}", name, remote_url, branch);
    println!("Repository '{}' registered for switching", repo_name);
    Ok(())
}

/// Upload changes
fn upload(message: String) -> anyhow::Result<()> {
    let repo_root = std::env::current_dir()?;
    let config = repo::config::RepoConfig::load(&repo_root)?;

    // Generate commit message
    let msg = if message.is_empty() {
        format!("Auto-commit: {}", chrono::Local::now().format("%Y-%m-%d %H:%M"))
    } else {
        message
    };

    // Create local commit
    println!("🔍 Detecting changes...");
    let commit = repo::commit::Commit::create(&repo_root, &config, &msg)?;

    // Push to remote
    println!("📤 Pushing to remote...");
    let current_branch = config.branch.current.as_ref().unwrap_or(&config.branch.main);
    remote::push(&config.remote, current_branch, &commit)?;

    // Output result
    println!("\n✅ Upload successful!");
    println!("Commit ID: {}", commit.id);
    println!("Message: {}", commit.message);
    Ok(())
}

/// View commit history
fn log() -> anyhow::Result<()> {
    let repo_root = std::env::current_dir()?;
    let commits = repo::commit::Commit::load_all(&repo_root)?;

    if commits.is_empty() {
        return Err(anyhow::anyhow!("No commit records available"));
    }

    println!("📜 Commit history (latest first):");
    for (i, commit) in commits.iter().enumerate() {
        println!("\n[{i}] ID: {}", commit.id);
        println!("   Author: {}", commit.author);
        println!("   Timestamp: {}", commit.timestamp);
        println!("   Message: {}", commit.message);
        println!("   Changes:");
        for (path, status) in &commit.changes {
            let status_str = match status {
                repo::change::FileStatus::Added => "Added",
                repo::change::FileStatus::Modified => "Modified",
                repo::change::FileStatus::Deleted => "Deleted",
            };
            println!("     - {status_str}: {:?}", path);
        }
    }
    Ok(())
}

/// Branch management command
fn branch_cmd(add: Option<String>, delete: Option<String>, name: Option<String>) -> anyhow::Result<()> {
    let repo_root = std::env::current_dir()?;
    
    if let Some(branch_name) = add {
        repo::branch::create_and_switch(&repo_root, &branch_name)?;
        println!("✅ Created and switched to branch: {}", branch_name);
    } else if let Some(branch_name) = delete {
        repo::branch::delete(&repo_root, &branch_name)?;
        println!("✅ Deleted branch: {}", branch_name);
    } else if let Some(branch_name) = name {
        repo::branch::switch(&repo_root, &branch_name)?;
        println!("✅ Switched to branch: {}", branch_name);
    } else {
        let current = repo::branch::get_current(&repo_root)?;
        let branches = repo::branch::list_all(&repo_root)?;
        println!("Current branch: {}", current);
        println!("All branches: {}", branches.join(", "));
    }
    Ok(())
}

/// Switch to different repository
fn change_to(repo_name: String) -> anyhow::Result<()> {
    let repo_path = registry::find_repo(&repo_name)?;
    std::env::set_current_dir(&repo_path)?;
    println!("✅ Switched to repository: {} at {}", repo_name, repo_path.display());
    Ok(())
}

/// Rebase commits
fn rebase_cmd(all: bool, range: Option<String>) -> anyhow::Result<()> {
    let repo_root = std::env::current_dir()?;
    
    if let Some(range_str) = range {
        if range_str == "fuck-base" {
            repo::branch::undo_rebase(&repo_root)?;
            println!("✅ Rebase undone successfully");
        } else if range_str.contains(" -> ") {
            let dates: Vec<&str> = range_str.split(" -> ").collect();
            if dates.len() == 2 {
                repo::branch::rebase_date_range(&repo_root, dates[0], dates[1])?;
                println!("✅ Rebased commits from {} to {}", dates[0], dates[1]);
            } else {
                return Err(anyhow::anyhow!("Invalid date range format. Use: YYYY-MM-DD -> YYYY-MM-DD"));
            }
        }
    } else if all {
        repo::branch::rebase_all(&repo_root)?;
        println!("✅ Rebased all local changes");
    } else {
        return Err(anyhow::anyhow!("Please specify --all or date range"));
    }
    Ok(())
}

/// Edit past commit message
fn reload_commit(commit_sha: String, message: String) -> anyhow::Result<()> {
    let repo_root = std::env::current_dir()?;
    repo::commit::edit_message(&repo_root, &commit_sha, &message)?;
    println!("✅ Updated commit {} with new message: {}", commit_sha, message);
    Ok(())
}